name: Anchore Scan for Container Sec via ADI
on: 
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: docker build . --file Dockerfile --tag nginx
    - uses: anchore/scan-action@v1
      with:
        image-reference: "nginx"
        dockerfile-path: "./Dockerfile"
        fail-build: true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AnchoreReports
        path: ./anchore-reports/